update with latest code generator
Azure/azure-sdk-for-go pull request #14774
Opened 2021-06-11 23:08 UTC by jhendrixMSFT

- [ ] The purpose of this PR is explained in this or a referenced issue.
- [ ] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [ ] Tests are included and/or updated for code changes.
- [ ] Updates to [CHANGELOG.md][] are included.
- [ ] MIT license headers are included in each file.
 
[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md

2021-06-16 10:02 UTC, ArcturusZhang requested changes
Could we also update the changelog (v0.1.1)?

2021-06-16 10:03 UTC, ArcturusZhang commented
Also why will this module be of version v0.2.0 instead of v0.1.1?

2021-06-16 14:36 UTC, jhendrixMSFT commented
There are breaking changes in the public surface area compared to some of the other modules.

2021-06-18 02:44 UTC, ArcturusZhang approved these changes

2021-06-18 22:06 UTC, merged