ci: add build and test with Go 1.19
Azure/azure-sdk-for-go pull request #18784
Opened 2022-08-04 03:49 UTC by tadelesh

Resolve: https://github.com/Azure/azure-sdk-for-go/issues/18783

2022-08-04 05:15 UTC, tadelesh commented
/azp run go - azcore - ci

2022-08-04 05:16 UTC, tadelesh commented
/azp run go - aztemplate - ci

2022-08-04 05:16 UTC, tadelesh commented
/azp run go - internal - resourcemanager - ci

2022-08-04 05:16 UTC, tadelesh commented
/azp run go - internal - ci

2022-08-04 17:08 UTC, RickWinter requested changes

2022-08-04 17:08 UTC, RickWinter commented on eng/pipelines/templates/stages/platform-matrix.json
> +      "1.18.2",
```suggestion
      "1.18.5",
```

2022-08-08 19:53 UTC, jhendrixMSFT commented
Superseded by https://github.com/Azure/azure-sdk-for-go/pull/18805

2022-08-08 19:53 UTC, closed without merging