[Release] sdk/resourcemanager/authorization/armauthorization/2.0.0
Azure/azure-sdk-for-go pull request #18890
Opened 2022-08-17 09:18 UTC by Alancere

https://github.com/Azure/azure-sdk-for-go/issues/18811

2022-08-19 01:45 UTC, tadelesh commented
Wait for .Net authorization GA.

2022-08-19 17:59 UTC, RickWinter requested changes
v2 releases are painful for customers.  We want to keep this on the v1.x path.

2022-08-22 02:43 UTC, tadelesh commented
> v2 releases are painful for customers. We want to keep this on the v1.x path.

The breakings contain required param removal, property ref change and operation removal from swagger. I don't think it is possible to make it 1.x.

2022-08-31 12:15 UTC, mblaschke-daimlertruck commented
Any progress here? Is there a way to get this merged in the next days?

2022-09-01 09:42 UTC, tadelesh commented
@RickWinter, I've use directive to mitigate most of the breakings. Only one orphan model not used is left. I think it could be ignored. You could see the new generated [SDK](https://github.com/azure-sdk/azure-sdk-for-go/pull/2716) here and directive [here](https://github.com/Azure/azure-rest-api-specs/blob/2c5470e59e29aea941cd6448a5cb6c182e0f834a/specification/authorization/resource-manager/readme.go.md?plain=1#L18-L49). @JeffreyRichter Could you help to confirm whether we could release it with 1.1.0?

2022-09-01 20:43 UTC, JeffreyRichter commented
Joel & I spoke about this today. Here's where we're at...
It is a reality today that swaggers have bugs, we generate a client and then the swagger gets fixed causing a breaking change in the client (even though the service itself has not changed).

So, if we ship a client V1.0.0 and then the swagger gets fixed, we ship a new client V1.0.1.
Now, let's say an app uses V1.0.1 and also uses another package that depends on V1.0.0 - the app can't build now because V1.0.0 & V1.0.1 can't be compiled together into a single app - this is a very bad place for a customer to be and so we can't do this and put them there.

So, **any** client library break **must** be done in a new major version so that the new major and old major can be compiled together into a single app.

Obviously, the best thing for us (service team and SDK teams) to do is to better validate our swaggers and fix bugs **before** we create and ship client libraries.

2022-09-16 21:54 UTC, mblaschke commented
Any progress here?

2022-09-19 04:53 UTC, tadelesh commented
> Any progress here?

We are double confirming with service team and will release the new version soon.

2022-09-20 02:06 UTC, tadelesh commented
@RickWinter Please sign off. .NET has released `package-2022-04-01` as stable and we also got confirmation from service team to release Go SDK.

2022-09-20 02:06 UTC, tadelesh approved these changes

2022-09-21 06:46 UTC, tadelesh commented
Release request: https://github.com/Azure/sdk-release-request/issues/3207

2022-09-23 00:11 UTC, jhendrixMSFT commented on sdk/resourcemanager/authorization/armauthorization/autorest.md
> +tag: package-2022-04-01
What tag was previously used?

2022-09-23 02:17 UTC, tadelesh commented on sdk/resourcemanager/authorization/armauthorization/autorest.md
> +tag: package-2022-04-01
`1.0.0` uses tag `package-2020-10-01`.

2022-09-23 06:54 UTC, tadelesh commented
All the breaking changes is from this [PR](https://github.com/Azure/azure-rest-api-specs/pull/19937) and approved in this [PR](https://github.com/Azure/azure-rest-api-specs-pr/pull/6248).
1. `Function *RoleAssignmentsClient.NewListForResourcePager parameter(s) have been changed from (string, string, string, string, string, *RoleAssignmentsClientListForResourceOptions) to (string, string, string, string, *RoleAssignmentsClientListForResourceOptions)`
New swagger [here](https://github.com/Azure/azure-rest-api-specs/blob/1d9c9c68844d2b5883621069d5bf0c958841782f/specification/authorization/resource-manager/Microsoft.Authorization/stable/2022-04-01/authorization-RoleAssignmentsCalls.json#L132). This operation's path params have been changed. Old version [here](https://github.com/Azure/azure-rest-api-specs/blob/1d9c9c68844d2b5883621069d5bf0c958841782f/specification/authorization/resource-manager/Microsoft.Authorization/stable/2015-07-01/authorization-RoleAssignmentsCalls.json#L37).
2. `Type of RoleAssignment.Properties has been changed from *RoleAssignmentPropertiesWithScope to *RoleAssignmentProperties`
`Struct RoleAssignmentPropertiesWithScope has been removed`
`Properties` of `RoleAssignment` model has been changed. Old one [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/authorization/resource-manager/Microsoft.Authorization/stable/2015-07-01/authorization-RoleAssignmentsCalls.json#L594). New one [here](https://github.com/Azure/azure-rest-api-specs/blob/1d9c9c68844d2b5883621069d5bf0c958841782f/specification/authorization/resource-manager/Microsoft.Authorization/stable/2022-04-01/authorization-RoleAssignmentsCalls.json#L654).
3. `Function *RoleAssignmentsClient.NewListPager has been removed`
`Struct RoleAssignmentsClientListOptions has been removed`
`Struct RoleAssignmentsClientListResponse has been removed`
An operation has been renamed. Old swagger [here](https://github.com/Azure/azure-rest-api-specs/blob/1d9c9c68844d2b5883621069d5bf0c958841782f/specification/authorization/resource-manager/Microsoft.Authorization/stable/2015-07-01/authorization-RoleAssignmentsCalls.json#L450). New one [here](https://github.com/Azure/azure-rest-api-specs/blob/1d9c9c68844d2b5883621069d5bf0c958841782f/specification/authorization/resource-manager/Microsoft.Authorization/stable/2022-04-01/authorization-RoleAssignmentsCalls.json#L37).
4. Struct PermissionAutoGenerated has been removed
`Permission` model has been changed to align with other `Permission` definition. Old one [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/authorization/resource-manager/Microsoft.Authorization/stable/2015-07-01/authorization-RoleDefinitionsCalls.json#L498). New one [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/authorization/resource-manager/Microsoft.Authorization/stable/2022-04-01/authorization-RoleDefinitionsCalls.json#L505).

2022-09-23 06:58 UTC, tadelesh commented
@jhendrixMSFT @RickWinter @JeffreyRichter I list all the breakings and please help to review.

2022-09-23 14:02 UTC, jhendrixMSFT approved these changes

2022-09-23 18:04 UTC, JeffreyRichter approved these changes

2022-09-27 03:24 UTC, merged