Add survey comment to new issues.
Azure/azure-sdk-for-go pull request #18925
Opened 2022-08-23 05:55 UTC by tadelesh

Add survey link to every issue and try to gather user feedback in a more active way.

2022-08-23 06:12 UTC, xboxeer commented
Add some context, I'm recently help dealing with dotnet SDK issues and once an issue is closed, I'll advise customer to fill a survey and tell us their over experience of our SDK, the response rate is higher than expect and already have customer willing to talk with us, so it is worth to do the same in Golang SDK since we lack external customer study.

2022-08-23 16:04 UTC, RickWinter requested changes

2022-08-23 16:04 UTC, RickWinter commented on .github/fabricbot.json
> +              "comment": "Hi @${issueAuthor}. Thank you for your feedback and we will look into it soon. Meanwhile, feel free to share your experience using the Azure SDK in this [survey](https://www
```suggestion
              "comment": "Hi @${issueAuthor}. Thank you for your feedback and we will look into it soon. Meanwhile, feel free to share your experience using the Azure SDK in this [survey](https://aka.ms/azsdk/go/issuesurvey)."
```

2022-08-23 16:06 UTC, RickWinter commented
This change seems reasonable.  I've switched it to an aka.ms link (already live) so that we can quickly change it everywhere should that necessity arise.

@sandeep-sen , @mikekistler Can you review the questions

2022-08-23 17:30 UTC, mikekistler approved these changes
Looks good! 👍

2022-08-24 00:01 UTC, xboxeer approved these changes

2022-08-24 03:13 UTC, lirenhe approved these changes

2022-08-24 05:04 UTC, xboxeer approved these changes

2022-08-29 17:41 UTC, RickWinter approved these changes

2022-08-29 17:42 UTC, merged