sdk/resourcemanager/cdn/armcdn live test
Azure/azure-sdk-for-go pull request #19512
Opened 2022-11-08 02:36 UTC by Alancere

2022-11-08 12:19 UTC, tadelesh requested changes

2022-11-08 12:19 UTC, tadelesh commented on sdk/resourcemanager/cdn/armcdn/testdata/recordings/TestAfdxTestSuite.json
> +                "validationToken": "67stsyhm0w1vdvz3txscpj4pzvv70jrl",
Please remove such token value.

2022-11-10 05:24 UTC, Alancere commented on sdk/resourcemanager/cdn/armcdn/testdata/recordings/TestAfdxTestSuite.json
> +                "validationToken": "67stsyhm0w1vdvz3txscpj4pzvv70jrl",
fix

2022-11-10 05:26 UTC, tadelesh approved these changes

2022-11-10 06:12 UTC, merged