[aznamespaces] Moving to new folder site, updating readme and autorest
Azure/azure-sdk-for-go pull request #22441
Opened 2024-02-23 02:34 UTC by richardpark-msft

Moving the package for Event Grid namespaces into it's own module folder, sibling to the other Event Grid packages that are coming (azsystemevents and azeventgrid, which will contain the client for "Event Grid Basic").

2024-02-23 02:36 UTC, richardpark-msft commented
/azp run prepare-pipelines

2024-02-23 17:32 UTC, richardpark-msft commented
/azp run go - aznamespaces

2024-02-23 21:49 UTC, richardpark-msft commented
/azp run go - aznamespaces

2024-02-26 19:11 UTC, richardpark-msft commented
@jhendrixMSFT  - the failures for the older azeventgrid pipeline can be ignored. Just an artifact of me moving these things around behind the back of the CI pipelines.

2024-02-26 21:18 UTC, jhendrixMSFT requested changes
I'd like to understand the release logistics and migration strategy.

Do we need to release an updated `azeventgrid` with a deprecation notice that users need to migrate to `aznamespaces`?
What's our obligation to fix issues in the existing `azeventgrid`? i.e. is there a window of time where we're required to, or can we just say "move to `aznamespaces`"?
Will we reset the version number to `v0.1.0` for `aznamespaces`?

2024-02-26 21:22 UTC, richardpark-msft commented
> I'd like to understand the release logistics and migration strategy.
> 
> Do we need to release an updated `azeventgrid` with a deprecation notice that users need to migrate to `aznamespaces`? 

Yes, the old package will just get one more publish to mark it as deprecated.

> What's our obligation to fix issues in the existing `azeventgrid`? i.e. is there a window of time where we're required to, or can we just say "move to `aznamespaces`"? 

It was a beta so I don't think we have any obligation - I'll just point them to aznamespaces.

> Will we reset the version number to `v0.1.0` for `aznamespaces`?

I wasn't thinking we'd reset it, but we could. Either way it'll have to go for one more beta since I need to add in some missing functionality.

2024-02-27 01:33 UTC, richardpark-msft commented
/azp run go - aznamespaces

2024-02-28 01:53 UTC, richardpark-msft commented
@jhendrixMSFT, I brought back the old modules files.

2024-02-28 17:21 UTC, chlowell commented on sdk/messaging/eventgrid/aznamespaces/CHANGELOG.md
> +- This module has been moved from it's previous location in `azeventgrid` to this location (`github.com/Azure/azure-sdk-for-go/sdk/messaging/eventgrid/aznamespaces`).
```suggestion
- This module has been moved from its previous location in `azeventgrid` to this location (`github.com/Azure/azure-sdk-for-go/sdk/messaging/eventgrid/aznamespaces`).
```

2024-02-28 17:21 UTC, chlowell commented on sdk/messaging/eventgrid/aznamespaces/README.md
> +[ms_pulldelivery]: https://learn.microsoft.com/azure/event-grid/concepts-pull-delivery
```suggestion
```

2024-02-28 17:21 UTC, chlowell commented on sdk/messaging/eventgrid/aznamespaces/README.md
> +[godoc_client]: https://aka.ms/azsdk/go/namespaces/pkg/#Client
```suggestion
```

2024-02-28 17:21 UTC, chlowell commented on sdk/messaging/eventgrid/aznamespaces/README.md
> +[cloud_shell_bash]: https://shell.azure.com/bash
```suggestion
```

2024-02-28 17:21 UTC, chlowell commented on sdk/messaging/eventgrid/aznamespaces/build.go
> +// +build go1.18
```suggestion
```

2024-02-28 21:20 UTC, RickWinter commented
> > I'd like to understand the release logistics and migration strategy.
> > Do we need to release an updated `azeventgrid` with a deprecation notice that users need to migrate to `aznamespaces`?
> 
> Yes, the old package will just get one more publish to mark it as deprecated.
> 
> > What's our obligation to fix issues in the existing `azeventgrid`? i.e. is there a window of time where we're required to, or can we just say "move to `aznamespaces`"?
> 
> It was a beta so I don't think we have any obligation - I'll just point them to aznamespaces.
> 
> > Will we reset the version number to `v0.1.0` for `aznamespaces`?
> 
> I wasn't thinking we'd reset it, but we could. Either way it'll have to go for one more beta since I need to add in some missing functionality.

It was a Beta so we can deprecate at our discretion.

I'd be in favor of starting at `v0.1.0`.  Gives a good impression of this is the new thing.

2024-02-28 21:23 UTC, jhendrixMSFT commented on sdk/messaging/eventgrid/aznamespaces/go.mod
> +go 1.20
Should be `1.18`, is this intentional?

2024-02-28 21:24 UTC, jhendrixMSFT commented
Is this identical to `azeventgrid`?

2024-02-28 21:44 UTC, richardpark-msft commented
> Member

Yes, minus the subpackage `publisher`.

2024-02-28 22:01 UTC, jhendrixMSFT commented
Does `azeventgrid/publisher` go away completely, or does that end up in `aznamespaces`?

2024-02-28 22:07 UTC, richardpark-msft commented
> Does `azeventgrid/publisher` go away completely, or does that end up in `aznamespaces`?

Publisher is going to be it's own module. So the package map, as of now:

* `messaging/azeventgrid/publisher` -> `messaging/eventgrid/azeventgrid` (this matches what the other languages have used the main Event Grid package for)
* `messaging/azeventgrid` -> `messaging/eventgrid/aznamespaces` (this is the new service)

We also now have an messaging/eventgrid/azsystemevents module as well which I hadn't published in any form yet.

2024-02-28 22:25 UTC, jhendrixMSFT approved these changes

2024-02-28 22:41 UTC, merged